//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class groove
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public groove()
        {
            this.pattern = new HashSet<pattern>();
        }
    
        public int GrooveID { get; set; }
        public Nullable<int> GrooveNum { get; set; }
        public Nullable<decimal> G1Depth { get; set; }
        public Nullable<decimal> G2Depth { get; set; }
        public Nullable<decimal> G3Depth { get; set; }
        public Nullable<decimal> G4Depth { get; set; }
        public Nullable<decimal> G5Depth { get; set; }
        public Nullable<decimal> G1Width { get; set; }
        public Nullable<decimal> G2Width { get; set; }
        public Nullable<decimal> G3Width { get; set; }
        public Nullable<decimal> G4Width { get; set; }
        public Nullable<decimal> G5Width { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pattern> pattern { get; set; }
    }
}
