//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcrsectiondimension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pcrsectiondimension()
        {
            this.structure = new HashSet<structure>();
            this.structure1 = new HashSet<structure>();
        }
    
        public int SectionID { get; set; }
        public Nullable<decimal> TG1 { get; set; }
        public Nullable<decimal> TG2 { get; set; }
        public Nullable<decimal> TG3 { get; set; }
        public Nullable<decimal> TBTMx { get; set; }
        public Nullable<decimal> DTRSB { get; set; }
        public Nullable<decimal> TTM { get; set; }
        public Nullable<decimal> TTRMx1 { get; set; }
        public Nullable<decimal> TTRMx2 { get; set; }
        public Nullable<decimal> TTRMx3 { get; set; }
        public Nullable<decimal> WAN { get; set; }
        public Nullable<decimal> TG12 { get; set; }
        public Nullable<decimal> TTRJx { get; set; }
        public Nullable<decimal> TGS { get; set; }
        public Nullable<decimal> TTNJx { get; set; }
        public Nullable<decimal> TWSWZx { get; set; }
        public Nullable<decimal> TTWSWZx { get; set; }
        public Nullable<decimal> TBEC { get; set; }
        public Nullable<decimal> HWT { get; set; }
        public Nullable<decimal> LWT { get; set; }
        public Nullable<decimal> HWSW { get; set; }
        public Nullable<decimal> LWSW { get; set; }
        public Nullable<decimal> H1RF { get; set; }
        public Nullable<decimal> H2RF { get; set; }
        public Nullable<decimal> L1RF { get; set; }
        public Nullable<decimal> L2RF { get; set; }
        public Nullable<decimal> LRFR { get; set; }
        public Nullable<decimal> H1P { get; set; }
        public Nullable<decimal> H2P { get; set; }
        public Nullable<decimal> L2P { get; set; }
        public Nullable<decimal> H3P { get; set; }
        public Nullable<decimal> L3P { get; set; }
        public Nullable<decimal> P1P { get; set; }
        public Nullable<decimal> O1P1B { get; set; }
        public Nullable<decimal> A1B { get; set; }
        public Nullable<decimal> A2B { get; set; }
        public Nullable<decimal> W1B { get; set; }
        public Nullable<decimal> W2B { get; set; }
        public Nullable<decimal> D1B2B { get; set; }
        public Nullable<decimal> PICP { get; set; }
        public Nullable<decimal> DSBCP { get; set; }
        public Nullable<decimal> HRC { get; set; }
        public Nullable<decimal> TRCZx1 { get; set; }
        public Nullable<decimal> TRCZx2 { get; set; }
        public Nullable<decimal> HBF { get; set; }
        public Nullable<decimal> TBFZx1 { get; set; }
        public Nullable<decimal> TBFZx2 { get; set; }
        public Nullable<decimal> HLBF { get; set; }
        public Nullable<decimal> TTZx { get; set; }
        public Nullable<decimal> LSW { get; set; }
        public Nullable<decimal> LRC { get; set; }
        public Nullable<decimal> HRCS { get; set; }
        public Nullable<decimal> TRCBD { get; set; }
        public Nullable<decimal> TTBD { get; set; }
        public Nullable<decimal> HCHAE { get; set; }
        public Nullable<decimal> HCHAI { get; set; }
        public Nullable<decimal> HFL { get; set; }
        public Nullable<decimal> LIL { get; set; }
        public Nullable<decimal> TUBD { get; set; }
        public Nullable<decimal> OSFSB { get; set; }
        public Nullable<decimal> LSF { get; set; }
        public Nullable<decimal> TSFZx { get; set; }
        public Nullable<decimal> TIL { get; set; }
        public Nullable<decimal> PeriI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structure> structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<structure> structure1 { get; set; }
    }
}
