//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pitch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pitch()
        {
            this.pattern = new HashSet<pattern>();
        }
    
        public int PitchID { get; set; }
        public Nullable<decimal> PitchA { get; set; }
        public Nullable<decimal> PitchB { get; set; }
        public Nullable<decimal> PitchC { get; set; }
        public Nullable<decimal> PitchD { get; set; }
        public Nullable<decimal> PitchE { get; set; }
        public Nullable<decimal> PitchF { get; set; }
        public Nullable<int> TotalPitchs { get; set; }
        public string PitchSequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pattern> pattern { get; set; }
    }
}
