//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubberstraindma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rubberstraindma()
        {
            this.t_dma = new HashSet<t_dma>();
            this.t_dma1 = new HashSet<t_dma>();
            this.t_dma2 = new HashSet<t_dma>();
            this.t_dma3 = new HashSet<t_dma>();
            this.t_dma4 = new HashSet<t_dma>();
            this.t_dma5 = new HashSet<t_dma>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Temp1 { get; set; }
        public Nullable<decimal> S1TanDelta1 { get; set; }
        public Nullable<decimal> S1E1 { get; set; }
        public Nullable<decimal> S5TanDelta1 { get; set; }
        public Nullable<decimal> S5E1 { get; set; }
        public Nullable<decimal> S10TanDelta1 { get; set; }
        public Nullable<decimal> S10E1 { get; set; }
        public Nullable<decimal> Temp2 { get; set; }
        public Nullable<decimal> S1TanDelta2 { get; set; }
        public Nullable<decimal> S1E2 { get; set; }
        public Nullable<decimal> S5TanDelta2 { get; set; }
        public Nullable<decimal> S5E2 { get; set; }
        public Nullable<decimal> S10TanDelta2 { get; set; }
        public Nullable<decimal> S10E2 { get; set; }
        public Nullable<decimal> Temp3 { get; set; }
        public Nullable<decimal> S1TanDelta3 { get; set; }
        public Nullable<decimal> S1E3 { get; set; }
        public Nullable<decimal> S5TanDelta3 { get; set; }
        public Nullable<decimal> S5E3 { get; set; }
        public Nullable<decimal> S10TanDelta3 { get; set; }
        public Nullable<decimal> S10E3 { get; set; }
        public Nullable<decimal> Temp4 { get; set; }
        public Nullable<decimal> S1TanDelta4 { get; set; }
        public Nullable<decimal> S1E4 { get; set; }
        public Nullable<decimal> S5TanDelta4 { get; set; }
        public Nullable<decimal> S5E4 { get; set; }
        public Nullable<decimal> S10TanDelta4 { get; set; }
        public Nullable<decimal> S10E4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma5 { get; set; }
    }
}
