//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubberproperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rubberproperty()
        {
            this.t_physicalproperty = new HashSet<t_physicalproperty>();
            this.t_physicalproperty1 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty2 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty3 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty4 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty5 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty6 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty7 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty8 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty9 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty10 = new HashSet<t_physicalproperty>();
            this.t_physicalproperty11 = new HashSet<t_physicalproperty>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Hardness { get; set; }
        public Nullable<decimal> M100 { get; set; }
        public Nullable<decimal> M300 { get; set; }
        public Nullable<decimal> TS { get; set; }
        public Nullable<decimal> Eb { get; set; }
        public Nullable<decimal> Density { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty11 { get; set; }
    }
}
