//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubbertempdma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rubbertempdma()
        {
            this.t_dma = new HashSet<t_dma>();
            this.t_dma1 = new HashSet<t_dma>();
            this.t_dma2 = new HashSet<t_dma>();
            this.t_dma3 = new HashSet<t_dma>();
            this.t_dma4 = new HashSet<t_dma>();
            this.t_dma5 = new HashSet<t_dma>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> CNeg25TanDelta { get; set; }
        public Nullable<decimal> CNeg25E { get; set; }
        public Nullable<decimal> C0TanDelta { get; set; }
        public Nullable<decimal> C0E { get; set; }
        public Nullable<decimal> C25TanDelta { get; set; }
        public Nullable<decimal> C25E { get; set; }
        public Nullable<decimal> C60TanDelta { get; set; }
        public Nullable<decimal> C60E { get; set; }
        public Nullable<decimal> MaxTanDelta { get; set; }
        public Nullable<decimal> MaxTanDeltaTemp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma5 { get; set; }
    }
}
