//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sideplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sideplate()
        {
            this.tire = new HashSet<tire>();
        }
    
        public int SideID { get; set; }
        public Nullable<decimal> CharHeight { get; set; }
        public Nullable<decimal> CharDepth { get; set; }
        public string CharStyle { get; set; }
        public Nullable<decimal> KnurlDepth { get; set; }
        public Nullable<decimal> KnurlDistance { get; set; }
        public string KnurlStyle { get; set; }
        public string PoreStyle { get; set; }
        public Nullable<decimal> PoreDiameter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tire> tire { get; set; }
    }
}
