//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class structure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public structure()
        {
            this.tire = new HashSet<tire>();
        }
    
        public int StructureID { get; set; }
        public Nullable<int> Belt1_ID { get; set; }
        public Nullable<int> Belt2_ID { get; set; }
        public Nullable<int> Belt3_ID { get; set; }
        public Nullable<int> Belt4_ID { get; set; }
        public Nullable<int> Belt0_ID { get; set; }
        public Nullable<int> Carcass1_ID { get; set; }
        public Nullable<int> Carcass2_ID { get; set; }
        public Nullable<int> Carcass3_ID { get; set; }
        public Nullable<int> Chafer_ID { get; set; }
        public Nullable<int> TBRUpperSectionID { get; set; }
        public Nullable<int> TBRLowerSectionID { get; set; }
        public Nullable<int> PCRUpperSectionID { get; set; }
        public Nullable<int> PCRLowerSectionID { get; set; }
        public string BeadStructure { get; set; }
        public string BeadConfig { get; set; }
        public Nullable<decimal> BeadDrawing { get; set; }
    
        public virtual pcrsectiondimension pcrsectiondimension { get; set; }
        public virtual pcrsectiondimension pcrsectiondimension1 { get; set; }
        public virtual rebar rebar { get; set; }
        public virtual rebar rebar1 { get; set; }
        public virtual rebar rebar2 { get; set; }
        public virtual rebar rebar3 { get; set; }
        public virtual rebar rebar4 { get; set; }
        public virtual rebar rebar5 { get; set; }
        public virtual rebar rebar6 { get; set; }
        public virtual rebar rebar7 { get; set; }
        public virtual rebar rebar8 { get; set; }
        public virtual tbrsectiondimension tbrsectiondimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tire> tire { get; set; }
        public virtual tbrsectiondimension tbrsectiondimension1 { get; set; }
    }
}
