//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_adhesiveforce
    {
        public string ID { get; set; }
        public string TireID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<decimal> IL_CC { get; set; }
        public Nullable<decimal> CC_SW { get; set; }
        public Nullable<decimal> CC_B1 { get; set; }
        public Nullable<decimal> B1_B2 { get; set; }
        public Nullable<decimal> B2_B0 { get; set; }
        public Nullable<decimal> B01_B02 { get; set; }
        public Nullable<decimal> B2_B3 { get; set; }
        public Nullable<decimal> B3_B4 { get; set; }
        public Nullable<decimal> B3_TRD { get; set; }
        public Nullable<decimal> B4_TRD { get; set; }
        public Nullable<decimal> B0_TRD { get; set; }
    
        public virtual tire tire { get; set; }
        public virtual t_condition t_condition { get; set; }
    }
}
