//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_condition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_condition()
        {
            this.t_adhesiveforce = new HashSet<t_adhesiveforce>();
            this.t_airimpermeability = new HashSet<t_airimpermeability>();
            this.t_beadforce = new HashSet<t_beadforce>();
            this.t_dma = new HashSet<t_dma>();
            this.t_staticload = new HashSet<t_staticload>();
            this.t_physicalproperty = new HashSet<t_physicalproperty>();
            this.t_peripheraldimensions = new HashSet<t_peripheraldimensions>();
            this.t_explode = new HashSet<t_explode>();
            this.t_scanprofile = new HashSet<t_scanprofile>();
            this.t_strength = new HashSet<t_strength>();
            this.t_contactground = new HashSet<t_contactground>();
            this.t_unseat = new HashSet<t_unseat>();
            this.t_staticstiffness = new HashSet<t_staticstiffness>();
            this.t_positionforce = new HashSet<t_positionforce>();
            this.t_electricalimpedance = new HashSet<t_electricalimpedance>();
            this.t_endurance = new HashSet<t_endurance>();
            this.t_rollingresistance = new HashSet<t_rollingresistance>();
            this.t_cp = new HashSet<t_cp>();
            this.t_saf = new HashSet<t_saf>();
            this.t_ct = new HashSet<t_ct>();
            this.t_swp = new HashSet<t_swp>();
            this.t_rpt = new HashSet<t_rpt>();
            this.t_relax = new HashSet<t_relax>();
            this.t_drs = new HashSet<t_drs>();
        }
    
        public int ConditionID { get; set; }
        public string RimID { get; set; }
        public string FacilityID { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> Loaded { get; set; }
        public Nullable<decimal> RadialVelocity { get; set; }
        public Nullable<decimal> LateralVelocity { get; set; }
        public Nullable<decimal> LongitudinalVelocity { get; set; }
        public Nullable<decimal> TorsionalVelocity { get; set; }
        public Nullable<decimal> AirSpeed { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public string PressureStyle { get; set; }
        public System.DateTime AirTest { get; set; }
        public string TestStandard { get; set; }
        public string MeasurementMethod { get; set; }
        public string Category { get; set; }
        public System.DateTime TestTime { get; set; }
        public System.DateTime TestTime2 { get; set; }
        public string Tester { get; set; }
        public Nullable<decimal> PlatenDiameter { get; set; }
        public Nullable<decimal> PlatenVelocity { get; set; }
        public string BriquettingType { get; set; }
        public Nullable<decimal> BriquettingVelocity { get; set; }
        public Nullable<decimal> ValueP { get; set; }
        public Nullable<decimal> TubeLength { get; set; }
        public Nullable<decimal> TubeDiameter { get; set; }
        public Nullable<decimal> SARate { get; set; }
        public Nullable<decimal> R0 { get; set; }
    
        public virtual rim rim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_adhesiveforce> t_adhesiveforce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_airimpermeability> t_airimpermeability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_beadforce> t_beadforce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_staticload> t_staticload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_peripheraldimensions> t_peripheraldimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_explode> t_explode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_scanprofile> t_scanprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_strength> t_strength { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_contactground> t_contactground { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_unseat> t_unseat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_staticstiffness> t_staticstiffness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_positionforce> t_positionforce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_electricalimpedance> t_electricalimpedance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_endurance> t_endurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_rollingresistance> t_rollingresistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_cp> t_cp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_saf> t_saf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ct> t_ct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_swp> t_swp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_rpt> t_rpt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_relax> t_relax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_drs> t_drs { get; set; }
    }
}
