//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_dma
    {
        public string ID { get; set; }
        public string TireID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<int> TreadTempID { get; set; }
        public Nullable<int> TreadStrainID { get; set; }
        public Nullable<int> SideTempID { get; set; }
        public Nullable<int> SideStrainID { get; set; }
        public Nullable<int> BaseTempID { get; set; }
        public Nullable<int> BaseStrainID { get; set; }
        public Nullable<int> BFTempID { get; set; }
        public Nullable<int> BFStrainID { get; set; }
        public Nullable<int> RCTempID { get; set; }
        public Nullable<int> RCStrainID { get; set; }
        public Nullable<int> SFTempID { get; set; }
        public Nullable<int> SFStrainID { get; set; }
    
        public virtual rubberstraindma rubberstraindma { get; set; }
        public virtual rubberstraindma rubberstraindma1 { get; set; }
        public virtual rubberstraindma rubberstraindma2 { get; set; }
        public virtual rubberstraindma rubberstraindma3 { get; set; }
        public virtual rubberstraindma rubberstraindma4 { get; set; }
        public virtual rubberstraindma rubberstraindma5 { get; set; }
        public virtual rubbertempdma rubbertempdma { get; set; }
        public virtual rubbertempdma rubbertempdma1 { get; set; }
        public virtual rubbertempdma rubbertempdma2 { get; set; }
        public virtual rubbertempdma rubbertempdma3 { get; set; }
        public virtual rubbertempdma rubbertempdma4 { get; set; }
        public virtual rubbertempdma rubbertempdma5 { get; set; }
        public virtual t_condition t_condition { get; set; }
        public virtual tire tire { get; set; }
    }
}
