//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_physicalproperty
    {
        public string ID { get; set; }
        public string TireID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<int> Tread_BID { get; set; }
        public Nullable<int> Tread_AID { get; set; }
        public Nullable<int> Side_BID { get; set; }
        public Nullable<int> Side_AID { get; set; }
        public Nullable<int> Base_BID { get; set; }
        public Nullable<int> Base_AID { get; set; }
        public Nullable<int> BF_BID { get; set; }
        public Nullable<int> BF_AID { get; set; }
        public Nullable<int> RC_BID { get; set; }
        public Nullable<int> RC_AID { get; set; }
        public Nullable<int> SF_BID { get; set; }
        public Nullable<int> SF_AID { get; set; }
        public string AgingCond { get; set; }
    
        public virtual rubberproperty rubberproperty { get; set; }
        public virtual rubberproperty rubberproperty1 { get; set; }
        public virtual rubberproperty rubberproperty2 { get; set; }
        public virtual rubberproperty rubberproperty3 { get; set; }
        public virtual rubberproperty rubberproperty4 { get; set; }
        public virtual rubberproperty rubberproperty5 { get; set; }
        public virtual rubberproperty rubberproperty6 { get; set; }
        public virtual rubberproperty rubberproperty7 { get; set; }
        public virtual rubberproperty rubberproperty8 { get; set; }
        public virtual rubberproperty rubberproperty9 { get; set; }
        public virtual rubberproperty rubberproperty10 { get; set; }
        public virtual rubberproperty rubberproperty11 { get; set; }
        public virtual t_condition t_condition { get; set; }
        public virtual tire tire { get; set; }
    }
}
