//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_rpt
    {
        public string ID { get; set; }
        public string TireID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<decimal> LStf { get; set; }
        public Nullable<decimal> LP { get; set; }
        public Nullable<decimal> LC { get; set; }
        public Nullable<decimal> PRLFAngle { get; set; }
        public Nullable<decimal> PRLF { get; set; }
        public Nullable<decimal> CRLF { get; set; }
        public Nullable<decimal> AStf { get; set; }
        public Nullable<decimal> AP { get; set; }
        public Nullable<decimal> AC { get; set; }
        public Nullable<decimal> PRATAngle { get; set; }
        public Nullable<decimal> PRAT { get; set; }
        public Nullable<decimal> CRAT { get; set; }
    
        public virtual t_condition t_condition { get; set; }
        public virtual tire tire { get; set; }
    }
}
