//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_strength
    {
        public string ID { get; set; }
        public string TireID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public string Result { get; set; }
        public Nullable<decimal> Force1 { get; set; }
        public Nullable<decimal> Displacement1 { get; set; }
        public Nullable<decimal> Energy1 { get; set; }
        public string ContactedRim1 { get; set; }
        public string Broken1 { get; set; }
        public Nullable<decimal> Force2 { get; set; }
        public Nullable<decimal> Displacement2 { get; set; }
        public Nullable<decimal> Energy2 { get; set; }
        public string ContactedRim2 { get; set; }
        public string Broken2 { get; set; }
        public Nullable<decimal> Force3 { get; set; }
        public Nullable<decimal> Displacement3 { get; set; }
        public Nullable<decimal> Energy3 { get; set; }
        public string ContactedRim3 { get; set; }
        public string Broken3 { get; set; }
        public Nullable<decimal> Force4 { get; set; }
        public Nullable<decimal> Displacement4 { get; set; }
        public Nullable<decimal> Energy4 { get; set; }
        public string ContactedRim4 { get; set; }
        public string Broken4 { get; set; }
        public Nullable<decimal> Force5 { get; set; }
        public Nullable<decimal> Displacement5 { get; set; }
        public Nullable<decimal> Energy5 { get; set; }
        public string ContactedRim5 { get; set; }
        public string Broken5 { get; set; }
    
        public virtual t_condition t_condition { get; set; }
        public virtual tire tire { get; set; }
    }
}
