//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [DbConfigurationType(typeof(MySql.Data.Entity.MySqlEFConfiguration))]
    public partial class ttdbEntities : DbContext
    {
        public ttdbEntities()
            : base("name=ttdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<groove> groove { get; set; }
        public virtual DbSet<pattern> pattern { get; set; }
        public virtual DbSet<pcrsectiondimension> pcrsectiondimension { get; set; }
        public virtual DbSet<pitch> pitch { get; set; }
        public virtual DbSet<rebar> rebar { get; set; }
        public virtual DbSet<rim> rim { get; set; }
        public virtual DbSet<rubberproperty> rubberproperty { get; set; }
        public virtual DbSet<rubberstraindma> rubberstraindma { get; set; }
        public virtual DbSet<rubbertempdma> rubbertempdma { get; set; }
        public virtual DbSet<sideplate> sideplate { get; set; }
        public virtual DbSet<structure> structure { get; set; }
        public virtual DbSet<t_adhesiveforce> t_adhesiveforce { get; set; }
        public virtual DbSet<t_airimpermeability> t_airimpermeability { get; set; }
        public virtual DbSet<t_beadforce> t_beadforce { get; set; }
        public virtual DbSet<t_condition> t_condition { get; set; }
        public virtual DbSet<t_contactground> t_contactground { get; set; }
        public virtual DbSet<t_cp> t_cp { get; set; }
        public virtual DbSet<t_ct> t_ct { get; set; }
        public virtual DbSet<t_dma> t_dma { get; set; }
        public virtual DbSet<t_drs> t_drs { get; set; }
        public virtual DbSet<t_electricalimpedance> t_electricalimpedance { get; set; }
        public virtual DbSet<t_endurance> t_endurance { get; set; }
        public virtual DbSet<t_explode> t_explode { get; set; }
        public virtual DbSet<t_peripheraldimensions> t_peripheraldimensions { get; set; }
        public virtual DbSet<t_physicalproperty> t_physicalproperty { get; set; }
        public virtual DbSet<t_positionforce> t_positionforce { get; set; }
        public virtual DbSet<t_relax> t_relax { get; set; }
        public virtual DbSet<t_rollingresistance> t_rollingresistance { get; set; }
        public virtual DbSet<t_rpt> t_rpt { get; set; }
        public virtual DbSet<t_saf> t_saf { get; set; }
        public virtual DbSet<t_scanprofile> t_scanprofile { get; set; }
        public virtual DbSet<t_staticload> t_staticload { get; set; }
        public virtual DbSet<t_staticstiffness> t_staticstiffness { get; set; }
        public virtual DbSet<t_strength> t_strength { get; set; }
        public virtual DbSet<t_swp> t_swp { get; set; }
        public virtual DbSet<t_unseat> t_unseat { get; set; }
        public virtual DbSet<tbrsectiondimension> tbrsectiondimension { get; set; }
        public virtual DbSet<tire> tire { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<vw_tire_amount> vw_tire_amount { get; set; }
    }
}
