//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tire()
        {
            this.t_adhesiveforce = new HashSet<t_adhesiveforce>();
            this.t_airimpermeability = new HashSet<t_airimpermeability>();
            this.t_beadforce = new HashSet<t_beadforce>();
            this.t_contactground = new HashSet<t_contactground>();
            this.t_cp = new HashSet<t_cp>();
            this.t_ct = new HashSet<t_ct>();
            this.t_dma = new HashSet<t_dma>();
            this.t_drs = new HashSet<t_drs>();
            this.t_electricalimpedance = new HashSet<t_electricalimpedance>();
            this.t_endurance = new HashSet<t_endurance>();
            this.t_explode = new HashSet<t_explode>();
            this.t_peripheraldimensions = new HashSet<t_peripheraldimensions>();
            this.t_physicalproperty = new HashSet<t_physicalproperty>();
            this.t_positionforce = new HashSet<t_positionforce>();
            this.t_relax = new HashSet<t_relax>();
            this.t_rollingresistance = new HashSet<t_rollingresistance>();
            this.t_rpt = new HashSet<t_rpt>();
            this.t_saf = new HashSet<t_saf>();
            this.t_scanprofile = new HashSet<t_scanprofile>();
            this.t_staticload = new HashSet<t_staticload>();
            this.t_staticstiffness = new HashSet<t_staticstiffness>();
            this.t_strength = new HashSet<t_strength>();
            this.t_swp = new HashSet<t_swp>();
            this.t_unseat = new HashSet<t_unseat>();
        }
    
        public string TireID { get; set; }
        public string TireID2 { get; set; }
        public string TireType { get; set; }
        public string PID { get; set; }
        public Nullable<System.DateTime> Batch { get; set; }
        public string RimID { get; set; }
        public Nullable<int> StructureID { get; set; }
        public Nullable<int> PatternID { get; set; }
        public Nullable<int> SideID { get; set; }
        public string Brand { get; set; }
        public string Size { get; set; }
        public Nullable<int> PlyRating { get; set; }
        public string LoadIndex { get; set; }
        public string SpeedSymbol { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> SinglePressure { get; set; }
        public Nullable<decimal> DoublePressure { get; set; }
        public Nullable<decimal> SingleLoad { get; set; }
        public Nullable<decimal> DoubleLoad { get; set; }
        public string PurchasePlace { get; set; }
        public string ProducingArea { get; set; }
        public Nullable<System.DateTime> ProducingTime { get; set; }
        public string Advantage { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual pattern pattern { get; set; }
        public virtual rim rim { get; set; }
        public virtual sideplate sideplate { get; set; }
        public virtual structure structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_adhesiveforce> t_adhesiveforce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_airimpermeability> t_airimpermeability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_beadforce> t_beadforce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_contactground> t_contactground { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_cp> t_cp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ct> t_ct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dma> t_dma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_drs> t_drs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_electricalimpedance> t_electricalimpedance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_endurance> t_endurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_explode> t_explode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_peripheraldimensions> t_peripheraldimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_physicalproperty> t_physicalproperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_positionforce> t_positionforce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_relax> t_relax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_rollingresistance> t_rollingresistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_rpt> t_rpt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_saf> t_saf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_scanprofile> t_scanprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_staticload> t_staticload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_staticstiffness> t_staticstiffness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_strength> t_strength { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_swp> t_swp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_unseat> t_unseat { get; set; }
    }
}
